# <center> Homework 1 / Filtering spam messages
 </center>
<div>
    <center> RAZAFINDRAZAKA Henintsoa </center>
    <center> Wang James </center>
    <center> ____________</center>
    <center> ING5 SI GR02 </center>
    <center> 02/10/2020 </center>
</div>

# 1 Tasks 
##### 1. Divide the data in two groups: training and test examples.

In [1]:
import os 
import numpy as np 
from collections import Counter 
from sklearn.metrics import confusion_matrix

In [2]:
data = [] 
with open('messages.txt') as m: 
        data += m
        
data_train = data[0:int(len(data)*0.8)]
data_test = data[int(len(data)*0.8):len(data)]

print("longueur de data_train: ", len(data_train))
print("longueur de data_test: ", len(data_test))

longueur de data_train:  4000
longueur de data_test:  1000


##### 2. Parse both the training and test examples to generate both the spam and ham data sets.

In [3]:
# spam : 1 & ham : 0
y_test = [] 
spam_data_test = []
ham_data_test = []
for i in data_test:
    if i.startswith('spam'):
        y_test += '1'
        spam_data_test.append(i)
    else:
        y_test += '0'
        ham_data_test.append(i)
        
y_train = [] 
spam_data_train = []
ham_data_train = []
for i in data_train:
    if i.startswith('spam'):
        y_train += '1'
        spam_data_train.append(i)
    else:
        y_train += '0'
        ham_data_train.append(i)

In [4]:
print("longueur de y_train: ", len(y_train))
print(Counter(y_train))
print("longueur de spam_data_train: ", len(spam_data_train))
print("longueur de ham_data_train: ", len(ham_data_train))

longueur de y_train:  4000
Counter({'0': 3454, '1': 546})
longueur de spam_data_train:  546
longueur de ham_data_train:  3454


In [5]:
print("longueur de y_test: ", len(y_test))
print(Counter(y_test))
print("longueur de spam_data_test: ", len(spam_data_test))
print("longueur de ham_data_test: ", len(ham_data_test))

longueur de y_test:  1000
Counter({'0': 874, '1': 126})
longueur de spam_data_test:  126
longueur de ham_data_test:  874


In [6]:
spam_data_test

['spam\tmoney!!! you r a lucky winner ! 2 claim your prize text money 2 88600 over £1million to give away ! ppt150x3+normal text rate box403 w1t1jy\n',
 'spam\tDear Matthew please call 09063440451 from a landline, your complimentary 4*Lux Tenerife holiday or £1000 CASH await collection. ppm150 SAE T&Cs Box334 SK38XH.\n',
 'spam\tUrgent! call 09061749602 from Landline. Your complimentary 4* Tenerife Holiday or £10,000 cash await collection SAE T&Cs BOX 528 HP20 1YF 150ppm 18+\n',
 'spam\tHow about getting in touch with folks waiting for company? Just txt back your NAME and AGE to opt in! Enjoy the community (150p/SMS)\n',
 'spam\tUr cash-balance is currently 500 pounds - to maximize ur cash-in now send GO to 86688 only 150p/msg. CC: 08718720201 PO BOX 114/14 TCR/W1\n',
 'spam\tFilthy stories and GIRLS waiting for your\n',
 'spam\tURGENT! We are trying to contact U. Todays draw shows that you have won a £800 prize GUARANTEED. Call 09050001808 from land line. Claim M95. Valid12hrs onl

##### 3. Generate a dictionary from the training data.

In [7]:
data_train

["ham\tYup i've finished c ü there...\n",
 'ham\tRemember to ask alex about his pizza\n',
 'ham\tNo da..today also i forgot..\n',
 'ham\tOla would get back to you maybe not today but I ve told him you can be his direct link in the US in getting cars he bids for online, you arrange shipping and you get a cut. Or U????? For a partnership where U????? Invest money for shipping and he takes care of the rest!U??Wud b self reliant soon dnt worry\n',
 "ham\tFwiw the reason I'm only around when it's time to smoke is that because of gas I can only afford to be around when someone tells me to be and that apparently only happens when somebody wants to light up\n",
 "ham\tHello, my boytoy! I made it home and my constant thought is of you, my love. I hope your having a nice visit but I can't wait till you come home to me ...*kiss*\n",
 'ham\tCongrats kano..whr s the treat maga?\n',
 'ham\tWho u talking about?\n',
 'ham\tYup...\n',
 'ham\tOk...\n',
 "ham\tU wake up already? Wat u doing? U picking u

In [8]:
import os 
import numpy as np 
from sklearn.metrics import confusion_matrix

# Cleaning data train
data_train_cl = []
for i in data_train:
    data_train_cl.append(i[4:len(i)-1])

all_words = [] 
for j in data_train_cl:
    words = j.split() # split en fonction d'un espace
    all_words += words
dictionary = Counter(all_words)
# print(dictionary)
print("longeur du dictionnaire: ",len(dictionary))

for item in list(dictionary): 
    #check si item est bien un string contenant que des alphabets
    if item.isalpha() == False: 
        del dictionary[item] 
    elif len(item) == 1: 
        del dictionary[item] 
# garde les 3000 mots les plus communs (les 3000 mots qui ont le + d'occurence)
dictionary = dictionary.most_common(3000)
print("longeur du dictionnaire: ",len(dictionary))
print(dictionary)

longeur du dictionnaire:  12843
longeur du dictionnaire:  3000
[('to', 1539), ('you', 1203), ('the', 871), ('and', 595), ('in', 565), ('is', 556), ('for', 475), ('my', 447), ('of', 425), ('your', 417), ('me', 407), ('on', 342), ('have', 334), ('that', 306), ('are', 303), ('it', 285), ('call', 278), ('or', 271), ('be', 250), ('not', 249), ('with', 247), ('at', 240), ('get', 235), ('will', 235), ('can', 218), ('so', 215), ('ur', 211), ('but', 198), ('You', 186), ('from', 183), ('do', 177), ('just', 173), ('up', 165), ('when', 164), ('this', 164), ('if', 162), ('go', 161), ('like', 157), ('all', 157), ('we', 152), ('was', 151), ('know', 151), ('out', 146), ('got', 145), ('now', 141), ('come', 138), ('am', 132), ('Call', 118), ('by', 115), ('want', 114), ('about', 113), ('only', 112), ('time', 109), ('need', 105), ('send', 104), ('still', 104), ('then', 103), ('How', 102), ('going', 102), ('If', 99), ('what', 99), ('text', 94), ('our', 92), ('So', 92), ('its', 91), ('been', 90), ('he', 89)

##### 4. Extract features from both the training data and test data.

In [9]:
# Cleaning data test
data_test_cl = []
for i in data_test:
    data_test_cl.append(i[4:len(i)-1])
data_test_cl

['K, wait chikku..il send aftr  &lt;#&gt; mins',
 "But I'm on a diet. And I ate 1 too many slices of pizza yesterday. Ugh I'm ALWAYS on a diet.",
 'K:)i will give my kvb acc details:)',
 'Oh all have to come ah?',
 '\tmoney!!! you r a lucky winner ! 2 claim your prize text money 2 88600 over £1million to give away ! ppt150x3+normal text rate box403 w1t1jy',
 "I'm really sorry i won't b able 2 do this friday.hope u can find an alternative.hope yr term's going ok:-)",
 'Congratulations ore mo owo re wa. Enjoy it and i wish you many happy moments to and fro wherever you go',
 'So do you have samus shoulders yet',
 "What time you think you'll have it? Need to know when I should be near campus",
 '\tDear Matthew please call 09063440451 from a landline, your complimentary 4*Lux Tenerife holiday or £1000 CASH await collection. ppm150 SAE T&Cs Box334 SK38XH.',
 'Then dun wear jeans lor...',
 'Since when, which side, any fever, any vomitin.',
 'K:)k.are you in college?',
 '\tUrgent! call 0906

In [10]:
def extract_features(data): 
    features_matrix = np.zeros((len(data), 3000))
    docID = 0
    for mail in data:
        words = mail.split() 
        for word in words: 
            wordID = 0 
            for i, d in enumerate(dictionary): 
                if d[0] == word: 
                    wordID = i 
                    features_matrix[docID, wordID] = words.count(word) 
        docID = docID + 1 
    return features_matrix

In [11]:
# Extract features from training data.
train_matrix = extract_features(data_train_cl)
print('taille de la matrice : ', train_matrix.shape)
train_matrix

taille de la matrice :  (4000, 3000)


array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [12]:
# Extract features from both the test data.
test_matrix = extract_features(data_test_cl)
print('taille de la matrice : ', test_matrix.shape)
test_matrix

taille de la matrice :  (1000, 3000)


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [13]:
# Cleaning spam data train
spam_data_train_cl = []
for i in spam_data_train:
    spam_data_train_cl.append(i[4:len(i)-1])
    
spam_train_matrix = extract_features(spam_data_train_cl)
print('taille de la matrice : ', spam_train_matrix.shape)
spam_train_matrix

taille de la matrice :  (546, 3000)


array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [3., 0., 1., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [14]:
# Cleaning ham data train
ham_data_train_cl = []
for i in ham_data_train:
    ham_data_train_cl.append(i[4:len(i)-1])
    
ham_train_matrix = extract_features(ham_data_train_cl)
print('taille de la matrice : ', ham_train_matrix.shape)
ham_train_matrix

taille de la matrice :  (3454, 3000)


array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

##### 5. Implement the Naive Bayes from scratch, fit the respective models to the training data.

In [30]:
alpha = 1

# φy = P(y(i) = 1) :
p_y_1 = (y_train.count('1') + alpha) / (len(y_train) + 2*alpha)
# p_y_0 = (y_train.count('0') + alpha) / (len(y_train) + 2*alpha)
p_y_0 = 1 - p_y_1


# φn|y=1 = P(xn = 1|y = 1) :
v1 =np.zeros((3000))
for j in range(spam_train_matrix.shape[1]):
    for i in range(spam_train_matrix.shape[0]):
        v1[j] += spam_train_matrix[i][j]

p_x_1_y_1 = (v1 + alpha) / (y_train.count('1') + 2*alpha)

# φn|y=0 = P(xn = 1|y = 0) :
v0 =np.zeros((3000))
for j in range(ham_train_matrix.shape[1]):
    for i in range(ham_train_matrix.shape[0]):
        v0[j] += ham_train_matrix[i][j]
    
p_x_1_y_0 = (v0 + alpha) / (y_train.count('0') + 2*alpha)

print('φy = P(y(i) = 1) =', p_y_1,'\n')
print('φy = P(y(i) = 0) =', p_y_0,'\n')

print('φn|y=1 = P(xn = 1|y = 1) = ', p_x_1_y_1,'\n')
print('φn|y=0 = P(xn = 1|y = 0) = ', p_x_1_y_0)

φy = P(y(i) = 1) = 0.1366816591704148 

φy = P(y(i) = 0) = 0.8633183408295853 

φn|y=1 = P(xn = 1|y = 1) =  [0.81751825 0.23905109 0.24635036 ... 0.00182482 0.00182482 0.00182482] 

φn|y=0 = P(xn = 1|y = 0) =  [0.31626157 0.31076389 0.21354167 ... 0.0005787  0.0005787  0.0005787 ]


In [43]:
# prediction_spam with Laplace smoothing technique :
proba_spam = (p_x_1_y_1 * p_y_1) / ((p_x_1_y_1 * p_y_1) + (p_x_1_y_0 * p_y_0))
# myround = np.vectorize(round)
print(proba_spam)

# prediction_ham with Laplace smoothing technique :
proba_ham = (p_x_1_y_0 * p_y_0) / ((p_x_1_y_1 * p_y_1) + (p_x_1_y_0 * p_y_0))
print(proba_ham)

[0.29040346 0.10856485 0.15443834 ... 0.33299185 0.33299185 0.33299185]
[0.70959654 0.89143515 0.84556166 ... 0.66700815 0.66700815 0.66700815]


In [51]:
target_spam = np.zeros(len(spam_train_matrix))
for email in spam_train_matrix:
    for i, word, proba in zip(range(len(spam_train_matrix)), email, proba_spam):
        if word != 0:
            if target_spam[i] == 0:
                target_spam[i] = proba
            else:
                target_spam[i] *= proba
print(len(target_spam))
target_spam

546


array([2.41302601e-169, 1.38022413e-112, 2.13466874e-092, 2.53871503e-063,
       9.13258874e-045, 1.76997495e-066, 4.32611449e-065, 4.22893846e-010,
       6.99811110e-052, 2.18607903e-058, 1.58844988e-016, 1.20016779e-043,
       9.61230762e-049, 1.63070997e-022, 5.23553144e-041, 1.11191981e-018,
       8.56175340e-040, 1.79145412e-038, 1.23845570e-028, 4.96262687e-017,
       1.84354947e-036, 1.25260764e-020, 8.95167398e-027, 6.24487447e-024,
       3.22126540e-019, 3.29282956e-016, 1.33389024e-027, 2.41195156e-008,
       1.60416736e-029, 7.32331065e-028, 9.37850214e-011, 1.28397760e-023,
       1.51539562e-012, 5.57318148e-009, 1.94511456e-024, 6.05087231e-014,
       6.51173630e-014, 1.04165703e-010, 8.05039085e-017, 3.40816509e-012,
       3.87997946e-007, 5.06681415e-011, 4.14157036e-021, 4.15240750e-004,
       6.30465535e-022, 1.42640857e-002, 2.67609942e-009, 1.19207730e-006,
       4.16305077e-016, 1.13260665e-012, 3.83798538e-007, 5.70570715e-018,
       2.32215491e-011, 1

In [52]:
target_ham = np.zeros(len(spam_train_matrix))
for email in spam_train_matrix:
    for i, word, proba in zip(range(len(spam_train_matrix)), email, proba_ham):
        if word != 0:
            if target_ham[i] == 0:
                target_ham[i] = proba
            else:
                target_ham[i] *= proba
print(len(target_ham))
target_ham

546


array([1.65046826e-47, 1.62334850e-06, 5.85351442e-09, 1.82369434e-05,
       3.67803173e-02, 2.90317751e-08, 6.64193236e-18, 9.35042809e-01,
       7.07413036e-05, 9.35254247e-24, 6.63393417e-01, 6.21552694e-12,
       8.18168810e-13, 3.18411672e-01, 3.84464869e-06, 4.72178489e-01,
       3.92028225e-38, 2.78007098e-41, 6.22158289e-03, 4.74737795e-01,
       8.26223923e-11, 2.30013685e-01, 1.98557749e-02, 4.33429866e-02,
       2.34809440e-01, 4.20757079e-01, 6.31986169e-11, 8.58931894e-01,
       2.13487915e-10, 2.97209632e-24, 6.31782394e-01, 1.92761071e-03,
       5.06431441e-01, 7.72508011e-01, 6.73628322e-05, 3.71733524e-01,
       3.69387578e-01, 6.27848911e-01, 1.30094113e-01, 4.77122226e-01,
       7.64816507e-01, 5.11450795e-01, 8.74815729e-04, 9.59660327e-01,
       5.76718408e-08, 9.85735914e-01, 6.50337807e-01, 8.79821242e-93,
       4.56158691e-04, 1.88319386e-01, 7.65274610e-01, 1.80611586e-05,
       2.84595267e-01, 7.13344492e-01, 1.47212741e-05, 7.47583084e-01,
      

In [54]:
TARGET = []
for i in (target_spam-target_ham):
    if i > 0:
        TARGET.append(1)
    else:
        TARGET.append(0)
TARGET

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


In [57]:
accuracy = 0
for target, y in zip(TARGET, y_train):
    if target == int(y):
        accuracy += 1
accuracy = accuracy / len(TARGET)
print(accuracy)

0.7765567765567766


##### 6. Make predictions for the test data.

In [59]:
target_spam = np.zeros(len(test_matrix))
for email in test_matrix:
    for i, word, proba in zip(range(len(test_matrix)), email, proba_spam):
        if word != 0:
            if target_spam[i] == 0:
                target_spam[i] = proba
            else:
                target_spam[i] *= proba
print(len(target_spam))
target_spam

1000


array([5.41403223e-157, 8.38897386e-188, 1.58789555e-130, 8.99609759e-121,
       1.15890799e-152, 4.00152951e-094, 1.87291437e-051, 3.33163274e-173,
       1.02225900e-078, 4.32616896e-038, 4.05310760e-127, 4.26096627e-043,
       3.68315328e-043, 1.86360528e-085, 2.02111476e-042, 2.92898531e-071,
       4.96896949e-017, 5.09709534e-019, 2.59485083e-052, 1.81046577e-073,
       2.92243871e-033, 4.48251388e-088, 1.28052517e-054, 3.89984572e-047,
       2.23127568e-058, 1.30465580e-068, 3.46407638e-026, 2.47893228e-072,
       4.79157359e-026, 6.56383634e-016, 4.04747424e-052, 3.22790130e-033,
       1.84724684e-057, 7.11653487e-049, 8.50715809e-024, 5.26273232e-058,
       2.83468247e-051, 1.20160400e-045, 1.19688021e-037, 4.89596927e-050,
       1.68415185e-031, 3.33944945e-052, 1.39142209e-028, 2.32273319e-068,
       1.83999654e-019, 2.10863546e-076, 1.03347159e-049, 6.89431405e-002,
       9.67511330e-014, 2.70701243e-028, 2.16976783e-026, 8.16151518e-016,
       1.15987378e-031, 8

In [60]:
target_ham = np.zeros(len(test_matrix))
for email in test_matrix:
    for i, word, proba in zip(range(len(test_matrix)), email, proba_ham):
        if word != 0:
            if target_ham[i] == 0:
                target_ham[i] = proba
            else:
                target_ham[i] *= proba
print(len(target_ham))
target_ham

1000


array([4.40902901e-44, 2.07688657e-10, 2.20416892e-12, 8.15482963e-10,
       1.12557225e-05, 1.96722725e-11, 2.89493519e-14, 2.90602605e-01,
       4.70383813e-07, 1.19443477e-15, 3.75119173e-02, 8.65269336e-12,
       2.08125982e-11, 1.16729161e-02, 2.48228494e-06, 5.24448588e-02,
       2.45096526e-16, 2.21802044e-20, 8.35716975e-05, 3.60152323e-02,
       6.60760745e-10, 1.58054841e-03, 3.00875320e-04, 1.87861449e-03,
       1.09172485e-02, 2.24658280e-02, 2.17526633e-10, 2.39448464e-01,
       3.13702441e-09, 6.85675317e-14, 9.50404612e-02, 1.40113200e-04,
       3.81679794e-02, 2.21871124e-01, 8.73304573e-05, 1.37300090e-02,
       2.19793797e-02, 1.23125542e-01, 9.28972448e-03, 4.15056753e-02,
       2.76105345e-01, 3.49960712e-02, 6.61636309e-05, 4.38885086e-01,
       4.00601165e-07, 5.54860459e-01, 8.55505622e-02, 8.91007302e-19,
       1.48969759e-03, 2.12168465e-02, 3.42980334e-01, 7.07379396e-05,
       2.58403675e-02, 2.26212695e-01, 4.32079424e-05, 2.94692957e-01,
      

In [61]:
TARGET = []
for i in (target_spam-target_ham):
    if i > 0:
        TARGET.append(1)
    else:
        TARGET.append(0)
TARGET

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


In [62]:
accuracy = 0
for target, y in zip(TARGET, y_test):
    if target == int(y):
        accuracy += 1
accuracy = accuracy / len(TARGET)
print(accuracy)

0.749


##### 7. Measure the spam-filtering performance for each approach through the confusion matrix.

##### 8. Discuss your results.