# <center> Homework 1 / Filtering spam messages
 </center>
<div>
    <center> RAZAFINDRAZAKA Henintsoa </center>
    <center> WANG James </center>
    <center> ____________</center>
    <center> ING5 SI GR02 </center>
    <center> 02/10/2020 </center>
</div>

### 1. Divide the data in two groups: training and test examples.

In [1]:
import os 
import numpy as np 
from collections import Counter 

In [2]:
data = [] 
with open('messages.txt') as m: 
        data += m
        
data_train = data[0:int(len(data)*0.8)]
data_test = data[int(len(data)*0.8):len(data)]

print("longueur de data_train: ", len(data_train))
print("longueur de data_test: ", len(data_test))

longueur de data_train:  4000
longueur de data_test:  1000


### 2. Parse both the training and test examples to generate both the spam and ham data sets.

In [3]:
# spam : 1 & ham : 0
y_test = [] 

for i in data_test:
    if i.startswith('spam'):
        y_test.append(1)
    else:
        y_test.append(0)
        
y_train = []

for i in data_train:
    if i.startswith('spam'):
        y_train.append(1)
    else:
        y_train.append(0)


In [4]:
print("longueur de y_train: ", len(y_train))
print(Counter(y_train))


longueur de y_train:  4000
Counter({0: 3454, 1: 546})


In [5]:
print("longueur de y_test: ", len(y_test))
print(Counter(y_test))


longueur de y_test:  1000
Counter({0: 874, 1: 126})


### 3. Generate a dictionary from the training data.

In [6]:
data_train

["ham\tYup i've finished c ü there...\n",
 'ham\tRemember to ask alex about his pizza\n',
 'ham\tNo da..today also i forgot..\n',
 'ham\tOla would get back to you maybe not today but I ve told him you can be his direct link in the US in getting cars he bids for online, you arrange shipping and you get a cut. Or U????? For a partnership where U????? Invest money for shipping and he takes care of the rest!U??Wud b self reliant soon dnt worry\n',
 "ham\tFwiw the reason I'm only around when it's time to smoke is that because of gas I can only afford to be around when someone tells me to be and that apparently only happens when somebody wants to light up\n",
 "ham\tHello, my boytoy! I made it home and my constant thought is of you, my love. I hope your having a nice visit but I can't wait till you come home to me ...*kiss*\n",
 'ham\tCongrats kano..whr s the treat maga?\n',
 'ham\tWho u talking about?\n',
 'ham\tYup...\n',
 'ham\tOk...\n',
 "ham\tU wake up already? Wat u doing? U picking u

##### Cleaning data_train

* Removing the "spam"/"ham", "\t" and "\n"

In [7]:
data_train_cl = []
for i,msg in zip(range(len(data_train)),data_train):
    if y_train[i] == 1:
        data_train_cl.append(msg[5:len(msg)-1])
    else:
        data_train_cl.append(msg[4:len(msg)-1])

data_train_cl

["Yup i've finished c ü there...",
 'Remember to ask alex about his pizza',
 'No da..today also i forgot..',
 'Ola would get back to you maybe not today but I ve told him you can be his direct link in the US in getting cars he bids for online, you arrange shipping and you get a cut. Or U????? For a partnership where U????? Invest money for shipping and he takes care of the rest!U??Wud b self reliant soon dnt worry',
 "Fwiw the reason I'm only around when it's time to smoke is that because of gas I can only afford to be around when someone tells me to be and that apparently only happens when somebody wants to light up",
 "Hello, my boytoy! I made it home and my constant thought is of you, my love. I hope your having a nice visit but I can't wait till you come home to me ...*kiss*",
 'Congrats kano..whr s the treat maga?',
 'Who u talking about?',
 'Yup...',
 'Ok...',
 "U wake up already? Wat u doing? U picking us up later rite? I'm taking sq825, reaching ard 7 smth 8 like dat. U can ch

* Creating a list of all words with their occurences

In [8]:
all_words = [] 

for j in data_train_cl:
    words = j.split() # split en fonction d'un espace
    all_words += words
dictionary = Counter(all_words)
print(dictionary)
#print("Number of words: ",len(dictionary))



Counter({'to': 1539, 'you': 1203, 'I': 1056, 'a': 974, 'the': 871, 'and': 595, 'in': 565, 'is': 556, 'i': 540, 'u': 502, 'for': 475, 'my': 447, 'of': 425, 'your': 417, 'me': 407, 'on': 342, 'have': 334, 'that': 306, '2': 303, 'are': 303, 'it': 285, 'call': 278, 'or': 271, 'be': 250, 'not': 249, 'with': 247, 'at': 240, 'get': 235, 'will': 235, 'can': 218, 'so': 215, 'ur': 211, "I'm": 210, 'U': 206, 'but': 198, '&lt;#&gt;': 192, 'You': 186, '4': 185, 'from': 183, 'do': 177, 'just': 173, 'up': 165, 'when': 164, 'this': 164, 'if': 162, 'go': 161, 'like': 157, 'all': 157, 'we': 152, 'was': 151, 'know': 151, 'out': 146, 'got': 145, 'now': 141, '.': 141, 'come': 138, 'am': 132, '?': 128, '...': 124, 'Call': 118, 'by': 115, 'want': 114, 'about': 113, 'only': 112, 'time': 109, 'need': 105, 'send': 104, 'still': 104, 'then': 103, 'How': 102, 'going': 102, 'If': 99, 'what': 99, 'n': 97, 'text': 94, 'our': 92, 'So': 92, 'its': 91, 'been': 90, "I'll": 90, 'he': 89, 'But': 89, 'We': 89, 'one': 88, '

* Removing the non-alphabetic and 1-letter words

In [9]:
for item in list(dictionary): 
    if item.isalpha() == False: 
        del dictionary[item] 
    elif len(item) == 1: 
        del dictionary[item]

print(dictionary)

Counter({'to': 1539, 'you': 1203, 'the': 871, 'and': 595, 'in': 565, 'is': 556, 'for': 475, 'my': 447, 'of': 425, 'your': 417, 'me': 407, 'on': 342, 'have': 334, 'that': 306, 'are': 303, 'it': 285, 'call': 278, 'or': 271, 'be': 250, 'not': 249, 'with': 247, 'at': 240, 'get': 235, 'will': 235, 'can': 218, 'so': 215, 'ur': 211, 'but': 198, 'You': 186, 'from': 183, 'do': 177, 'just': 173, 'up': 165, 'when': 164, 'this': 164, 'if': 162, 'go': 161, 'like': 157, 'all': 157, 'we': 152, 'was': 151, 'know': 151, 'out': 146, 'got': 145, 'now': 141, 'come': 138, 'am': 132, 'Call': 118, 'by': 115, 'want': 114, 'about': 113, 'only': 112, 'time': 109, 'need': 105, 'send': 104, 'still': 104, 'then': 103, 'How': 102, 'going': 102, 'If': 99, 'what': 99, 'text': 94, 'our': 92, 'So': 92, 'its': 91, 'been': 90, 'he': 89, 'But': 89, 'We': 89, 'one': 88, 'as': 88, 'see': 87, 'No': 86, 'there': 83, 'good': 82, 'Just': 81, 'some': 80, 'how': 79, 'no': 79, 'has': 79, 'home': 78, 'Do': 78, 'an': 78, 'back': 77,

* Keeping only the 3 000 most common words

In [10]:
dictionary = dictionary.most_common(3000)
print("Dictionnary's length: ",len(dictionary))
print(dictionary)

Dictionnary's length:  3000
[('to', 1539), ('you', 1203), ('the', 871), ('and', 595), ('in', 565), ('is', 556), ('for', 475), ('my', 447), ('of', 425), ('your', 417), ('me', 407), ('on', 342), ('have', 334), ('that', 306), ('are', 303), ('it', 285), ('call', 278), ('or', 271), ('be', 250), ('not', 249), ('with', 247), ('at', 240), ('get', 235), ('will', 235), ('can', 218), ('so', 215), ('ur', 211), ('but', 198), ('You', 186), ('from', 183), ('do', 177), ('just', 173), ('up', 165), ('when', 164), ('this', 164), ('if', 162), ('go', 161), ('like', 157), ('all', 157), ('we', 152), ('was', 151), ('know', 151), ('out', 146), ('got', 145), ('now', 141), ('come', 138), ('am', 132), ('Call', 118), ('by', 115), ('want', 114), ('about', 113), ('only', 112), ('time', 109), ('need', 105), ('send', 104), ('still', 104), ('then', 103), ('How', 102), ('going', 102), ('If', 99), ('what', 99), ('text', 94), ('our', 92), ('So', 92), ('its', 91), ('been', 90), ('he', 89), ('But', 89), ('We', 89), ('one', 

### 4. Extract features from both the training data and test data.

* Removing the "spam"/"ham", "\t" and "\n"

In [11]:
# Cleaning data test
data_test_cl = []
for i,msg in zip(range(len(data_test)),data_test):
    if y_test[i] == 1:
        data_test_cl.append(msg[5:len(msg)-1])
    else:
        data_test_cl.append(msg[4:len(msg)-1])

data_test_cl

['K, wait chikku..il send aftr  &lt;#&gt; mins',
 "But I'm on a diet. And I ate 1 too many slices of pizza yesterday. Ugh I'm ALWAYS on a diet.",
 'K:)i will give my kvb acc details:)',
 'Oh all have to come ah?',
 'money!!! you r a lucky winner ! 2 claim your prize text money 2 88600 over £1million to give away ! ppt150x3+normal text rate box403 w1t1jy',
 "I'm really sorry i won't b able 2 do this friday.hope u can find an alternative.hope yr term's going ok:-)",
 'Congratulations ore mo owo re wa. Enjoy it and i wish you many happy moments to and fro wherever you go',
 'So do you have samus shoulders yet',
 "What time you think you'll have it? Need to know when I should be near campus",
 'Dear Matthew please call 09063440451 from a landline, your complimentary 4*Lux Tenerife holiday or £1000 CASH await collection. ppm150 SAE T&Cs Box334 SK38XH.',
 'Then dun wear jeans lor...',
 'Since when, which side, any fever, any vomitin.',
 'K:)k.are you in college?',
 'Urgent! call 0906174960

In [12]:
def extract_features(data): 
    features_matrix = np.zeros((len(data), 3000))
    docID = 0
    for mail in data:
        words = mail.split() 
        for word in words: 
            wordID = 0 
            for i, d in enumerate(dictionary): 
                if d[0] == word: 
                    wordID = i 
                    features_matrix[docID, wordID] = words.count(word) 
        docID = docID + 1 
    return features_matrix

* Extract features from training data.


In [13]:
x_train = extract_features(data_train_cl)
print('x_train shape : ', x_train.shape)
x_train

x_train shape :  (4000, 3000)


array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

* Extract features from test data.


In [14]:
x_test = extract_features(data_test_cl)
print('x_test shape : ', x_test.shape)
x_test

x_test shape :  (1000, 3000)


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

### 5. Implement the Naive Bayes from scratch, fit the respective models to the training data.

#### Definition of α (Laplace smoothing technique variable)  

In [195]:
alpha = 0.06
D = len(dictionary)

#### P(y = 1)

In [196]:
# I = number of messages
I = len(y_train)

# indicator function for {y=1}
I_y1 = y_train.count(1)

P_y1 = (I_y1 + alpha)/(I + 2*alpha)

print(' P(y=1) = ',P_y1)

 P(y=1) =  0.1365109046728598


#### P(y = 0)

In [197]:
# indicator function for {y=0}
I_y0 = y_train.count(0)

P_y0 = 1 - P_y1

print("P(y=0) = ", P_y0)

P(y=0) =  0.8634890953271401


#### P(xn = 1|y = 1)


In [198]:
# Indicator function for {xn=1,y=1}
I_x1_y1 = np.zeros(len(dictionary))

# Creation of a matrix with both y and x 
y_train_np = np.reshape(y_train, (4000,1))

yx_train = np.concatenate((y_train_np,x_train), axis=1)

# Calculation of the indicator function
for col in range(1,yx_train.shape[1]):
    for li in range(yx_train.shape[0]):
        if yx_train[li][0] == 1:    # if y=1
            I_x1_y1[col-1] += yx_train[li][col]
            
phi_y1 = (I_x1_y1 + alpha) / (I_y1 + alpha * D)

phi_y1

array([6.15785124e-01, 1.79146006e-01, 1.84655647e-01, ...,
       8.26446281e-05, 8.26446281e-05, 8.26446281e-05])

#### P(xn = 1|y = 0)


In [199]:
# Indicator function for {xn=1,y=0}
I_x1_y0 = np.zeros(len(dictionary))

for col in range(1,yx_train.shape[1]):
    for li in range(yx_train.shape[0]):
        if yx_train[li][0] == 0:
            I_x1_y0[col-1] += yx_train[li][col]
            
phi_y0 = (I_x1_y0 + alpha) / (I_y0 + alpha * D)

phi_y0

array([3.00511833e-01, 2.95283434e-01, 2.02823335e-01, ...,
       2.91689598e-04, 2.91689598e-04, 2.91689598e-04])

#### P(x|y = 1)


In [200]:
spam_train = np.zeros(y_train_np.shape[0])

for li in range(x_train.shape[0]):
    index = []
    prod = 1
    for col in range(x_train.shape[1]):
        if x_train[li][col] != 0:
            index.append(col)
    for i in index:
        prod *= phi_y1[i]
        
    spam_train[li] = prod

spam_train


array([6.83013455e-09, 2.92328294e-22, 1.62094271e-05, ...,
       6.05256798e-12, 1.46539959e-23, 3.36012072e-15])

#### P(x|y = 0)


In [201]:
ham_train = np.zeros(y_train_np.shape[0])

for li in range(x_train.shape[0]):
    index = []
    prod = 1
    for col in range(x_train.shape[1]):
        if x_train[li][col] != 0:
            index.append(col)
    for i in index:
        prod *= phi_y0[i]
        
    ham_train[li] = prod

ham_train

array([2.88100006e-05, 5.74753817e-16, 1.89505675e-04, ...,
       6.81228971e-10, 7.54577910e-17, 3.83374814e-11])

#### P(y = 1|x)

In [202]:
P_y1_x = (spam_train * P_y1) / ( spam_train * P_y1 + ham_train * P_y0 )

P_y1_x

array([3.74783276e-05, 8.04080334e-08, 1.33420497e-02, ...,
       1.40264403e-03, 3.07017021e-08, 1.38559329e-05])

#### P(y = 0|x)


In [203]:
P_y0_x = (ham_train * P_y0) / ( spam_train * P_y1 + (ham_train * P_y0))

P_y0_x

array([0.99996252, 0.99999992, 0.98665795, ..., 0.99859736, 0.99999997,
       0.99998614])

In [204]:
target_train = []

for i in range(len(P_y1_x)):
    if P_y1_x[i] < P_y0_x[i]:
        target_train.append(0)
    else: 
        target_train.append(1)
    
target_train

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


### 6. Make predictions for the test data.

#### P(x|y = 1)


In [205]:
spam_test = np.zeros(x_test.shape[0])

for li in range(x_test.shape[0]):
    index = []
    prod = 1
    for col in range(x_test.shape[1]):
        if x_test[li][col] != 0:
            index.append(col)
    for i in index:
        prod *= phi_y1[i]
        
    spam_test[li] = prod

spam_test


array([6.36042325e-008, 6.26424210e-026, 1.20062978e-010, 3.91150994e-009,
       2.43466109e-024, 5.92393515e-025, 1.12720133e-032, 1.17444559e-009,
       2.50801631e-024, 1.26241344e-019, 9.97237276e-012, 2.44203339e-008,
       1.08721391e-002, 1.09991410e-019, 9.41789335e-044, 2.81949070e-032,
       1.05323257e-022, 1.16502302e-034, 1.24348104e-050, 1.31136324e-052,
       9.51790337e-021, 2.57012890e-020, 2.38528956e-050, 5.94013691e-003,
       2.06789525e-013, 2.68547565e-013, 1.46005510e-003, 2.02480738e-052,
       3.31070819e-016, 5.20694971e-005, 2.95696468e-044, 3.13492333e-038,
       6.83013455e-009, 2.80504920e-037, 8.26446281e-005, 2.01820941e-012,
       1.08332994e-023, 4.20786793e-032, 1.85680592e-021, 1.61112428e-012,
       7.73416648e-038, 3.13588480e-023, 1.92282945e-061, 7.26734241e-010,
       1.02443859e-022, 2.70169066e-031, 5.72198114e-014, 4.27991606e-017,
       3.84419861e-007, 3.53573299e-006, 4.41558851e-049, 1.94384886e-015,
       1.76120858e-074, 2

#### P(x|y = 0)


In [206]:
ham_test = np.zeros(x_test.shape[0])

for li in range(x_test.shape[0]):
    index = []
    prod = 1
    for col in range(x_test.shape[1]):
        if x_test[li][col] != 0:
            index.append(col)
    for i in index:
        prod *= phi_y0[i]
        
    ham_test[li] = prod

ham_test

array([4.28405017e-007, 7.02274639e-016, 6.63367426e-008, 3.12753373e-007,
       2.68270621e-035, 3.90290138e-020, 3.89526562e-028, 7.48110982e-008,
       7.99835054e-020, 4.15084205e-036, 4.54107366e-008, 1.02023090e-007,
       4.23391266e-002, 2.56312617e-042, 4.65192354e-030, 1.34213453e-027,
       1.52904240e-018, 1.13452794e-039, 1.81110088e-039, 4.23188890e-041,
       3.22312538e-014, 2.77727532e-034, 4.15609572e-043, 5.52626887e-003,
       1.39536233e-010, 1.44352595e-009, 9.92294992e-003, 5.89640882e-037,
       2.70885529e-012, 4.66037784e-006, 1.72612543e-032, 2.10985491e-029,
       1.38924891e-005, 8.44799525e-036, 7.72151899e-003, 3.69996412e-009,
       3.46617723e-048, 4.38443440e-024, 3.92390670e-017, 1.33954300e-009,
       8.39267257e-025, 4.77201217e-018, 2.12192532e-049, 4.10868859e-009,
       1.06049047e-018, 1.25291894e-019, 5.73079440e-011, 1.76571918e-011,
       7.28647882e-007, 2.24613500e-005, 1.26493913e-034, 1.24286605e-009,
       1.62539204e-055, 9

#### P(y = 1|x)

In [207]:
P_y1_x_test = (spam_test * P_y1) / ( spam_test * P_y1 + (ham_test * P_y0))

P_y1_x_test

array([2.29332802e-02, 1.41017183e-11, 2.86049510e-04, 1.97330892e-03,
       1.00000000e+00, 2.39956304e-06, 4.57480845e-06, 2.47571606e-03,
       4.95722073e-06, 1.00000000e+00, 3.47164547e-05, 3.64613505e-02,
       3.90122885e-02, 1.00000000e+00, 3.20060211e-15, 3.32111307e-06,
       1.08895644e-05, 9.99938405e-01, 1.08544298e-12, 4.89890747e-13,
       4.66846985e-08, 1.00000000e+00, 9.07331629e-09, 1.45249399e-01,
       2.34234191e-04, 2.94099534e-05, 2.27327654e-02, 5.42883468e-17,
       1.93213379e-05, 6.38510705e-01, 2.70822207e-13, 2.34900976e-10,
       7.77187716e-05, 5.22183989e-03, 1.68922745e-03, 8.62266973e-05,
       1.00000000e+00, 1.51725651e-09, 7.48092119e-06, 1.90107960e-04,
       1.45687981e-14, 1.03888767e-06, 1.43258749e-13, 2.72022874e-02,
       1.52715464e-05, 3.40896965e-13, 1.57824177e-04, 3.83198621e-07,
       7.69852034e-02, 2.42816702e-02, 5.51860682e-16, 2.47256975e-07,
       1.71302283e-20, 2.53754670e-01, 4.17800652e-04, 3.78686112e-10,
      

#### P(y = 0|x)


In [208]:

P_y0_x_test = (ham_test * P_y0) / ( spam_test * P_y1 + (ham_test * P_y0))

P_y0_x_test

array([9.77066720e-01, 1.00000000e+00, 9.99713950e-01, 9.98026691e-01,
       6.96986090e-11, 9.99997600e-01, 9.99995425e-01, 9.97524284e-01,
       9.99995043e-01, 2.07981214e-16, 9.99965284e-01, 9.63538650e-01,
       9.60987711e-01, 1.47401102e-22, 1.00000000e+00, 9.99996679e-01,
       9.99989110e-01, 6.15947151e-05, 1.00000000e+00, 1.00000000e+00,
       9.99999953e-01, 6.83523644e-14, 9.99999991e-01, 8.54750601e-01,
       9.99765766e-01, 9.99970590e-01, 9.77267235e-01, 1.00000000e+00,
       9.99980679e-01, 3.61489295e-01, 1.00000000e+00, 1.00000000e+00,
       9.99922281e-01, 9.94778160e-01, 9.98310773e-01, 9.99913773e-01,
       2.02385564e-24, 9.99999998e-01, 9.99992519e-01, 9.99809892e-01,
       1.00000000e+00, 9.99998961e-01, 1.00000000e+00, 9.72797713e-01,
       9.99984728e-01, 1.00000000e+00, 9.99842176e-01, 9.99999617e-01,
       9.23014797e-01, 9.75718330e-01, 1.00000000e+00, 9.99999753e-01,
       1.00000000e+00, 7.46245330e-01, 9.99582199e-01, 1.00000000e+00,
      

In [209]:
target_test = []

for i in range(len(P_y1_x_test)):
    if P_y1_x_test[i] < P_y0_x_test[i]:
        target_test.append(0)
    else: 
        target_test.append(1)
    
target_test

[0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


### 7. Measure the spam-filtering performance for each approach through the confusion matrix.

In [210]:
def myConfusionMatrix(predicted,actual):
    
    TP = 0
    FP = 0
    FN = 0
    TN = 0

    for i in range(len(predicted)):
        if predicted[i] == 1 and int(actual[i]) == 1:
            TP += 1
        elif predicted[i] == 1 and int(actual[i]) == 0:
            FP += 1
        elif predicted[i] == 0 and int(actual[i]) == 1:
            FN += 1
        else:
            TN += 1
            
    Accuracy = (TP+TN)/(TP+FP+FN+TN)
    Precision = TP/(TP+FP)
    Recall = TP/(TP+FN)
    F1Score = 2*(Recall * Precision) / (Recall + Precision)
    
    print(['TP','FP'])
    print(['FN','TN'], '\n')
    print(np.array([[TP, FP],[FN, TN]]), '\n')
    
    print('Accuracy = ',Accuracy ,
          '\nPrecision = ',Precision,
          '\nRecall = ',Recall,
          '\nF1 Score = ',F1Score
         )
    return np.array([[TP, FP],[FN, TN]])


### Performances for the training set

In [211]:
myConfusionMatrix(target_train, y_train)

['TP', 'FP']
['FN', 'TN'] 

[[ 526   44]
 [  20 3410]] 

Accuracy =  0.984 
Precision =  0.9228070175438596 
Recall =  0.9633699633699634 
F1 Score =  0.9426523297491041


array([[ 526,   44],
       [  20, 3410]])

### Performances for the testing set

In [212]:
myConfusionMatrix(target_test, y_test)

['TP', 'FP']
['FN', 'TN'] 

[[118  21]
 [  8 853]] 

Accuracy =  0.971 
Precision =  0.8489208633093526 
Recall =  0.9365079365079365 
F1 Score =  0.8905660377358492


array([[118,  21],
       [  8, 853]])

### 8. Discuss your results.